### GENERAL SETTINGS ###

# Site settings
title: Elite Production
description: "Elite production est une société de production audiovisuelle basée entre la Martinique et Paris qui propose des reportages multi-formats pour les chaines de télévisions, les institutions ou les entreprises."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://eliteproduction.fr"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#3C4144" #"#349B89" #"#00b3fe" 
  primary_rgb: "60,65,68" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#000000" #"#1e1f20" #"#384452"
  link: "#f16162"
  link_hover: "#f16162"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/profile/view?id=AAIAAAMcxUMBR1q5lDLZwabnYFuLV4bdACTkREA&trk=nav_responsive_tab_profile
  - title: facebook
    url: https://www.facebook.com/pages/Elite-Production/453495611503801?sk=timeline
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Palais des Congrès de Madiana
    - 97233 SCHOELCHER
email: elizealexandra@gmail.com
tel: +596 696 22 25 26


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Alexandra Elize
    text: Diplômée de l'ESSEC Business School, titulaire d'un Master 2 en journalisme (ESJ Paris) et d'un Master de Droit des Affaires (Paris X), Alexandra est d'une grande polyvalence. JRI, présentatrice et réalisatrice, elle a acquis son expérience dans de nombreux médias, Antenne Réunion, BFM Tv, Eurosport, ATV et RCI. Elle s'est très vite démarquée dans le journalisme d'investigation, sa passion.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:elizealexandra@gmail.com
  - name: Angelique Elize
    text: Diplômée de l'ESC Reims cursus Grande Ecole, Angélique est une passionnée d'image et des médias en général. Après avoir travaillé dans une société de production cinématographique chez QUAD (Les Intouchables), elle enchaîne dans une société de production audiovisuelle, Ligne de Front (Enquête Exclusive) puis à New York chez Keep In News en tant que journaliste. Sa passion, le travail de l'image et la créativité.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:elizeangelique@gmail.com
    
# Clients information. Shown on Home and About pages.
clients:
  - name: Région Martinique
    img: regionmq.png
  - name: ATV
    img: atv.png
  - name: France Ô
    img: franceo.png
  - name: Total caraibes
    img: total.png
  - name: Indies Live
    img: indies.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Elite production est une société de production audiovisuelle basée entre la Martinique et Paris qui propose des reportages multi-formats pour les chaines de télévisions, les institutions ou les entreprises."